name: "Continuous Integration"

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v5
        with:
          node-version: "24"
          cache: "pnpm"
      - name: Install deps
        run: pnpm install
      - name: Biome CI
        run: pnpm run check
      - name: Build
        run: pnpm run build
