name: "Continuous Integration"

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: "24"
          cache: "npm"
      - name: Install deps
        run: npm ci
      - name: Biome CI
        run: npm run check
      - name: Build
        run: npm run build
