name: Publish Package to npmjs
on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      attestations: write
      packages: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v5
      - uses: denoland/setup-deno@v2
      - uses: oven-sh/setup-bun@v2
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v5
        with:
          node-version: "24"
          cache: "pnpm"
      - name: Install deps
        run: pnpm install
      - name: Biome CI
        run: pnpm run check
      - name: Build
        run: pnpm run build
      - uses: changesets/action@e0145edc7d9d8679003495b11f87bd8ef63c0cba # v1.5.3
        with:
          version: pnpm ci:version
          publish: pnpm ci:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true

      - run: pnpm publish:jsr
